name: Deploy to GitHub Pages
on:
  workflow_run:
    workflows: [ Build project ]
    types: [ completed ]
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Execute Gradle Webpack production build
        run: gradle browserProductionWebpack
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/distributions
          token: ${{ secrets.ACCESS_TOKEN }}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'